package runtime

import (
	"bufio"
	"bytes"
	"fmt"
	"log/slog"
	"maps"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type Nuxt struct {
	Log *slog.Logger
}

func (d *Nuxt) Name() RuntimeName {
	return RuntimeNameNuxt
}

func (d *Nuxt) Match(path string) bool {
	checkPaths := []string{
		filepath.Join(path, "nuxt.config.ts"),
		filepath.Join(path, "nuxt.config.js"),
		filepath.Join(path, "nuxt.config.mjs"),
		filepath.Join(path, "nuxt.config.mts"),
		filepath.Join(path, "nuxt.config.cjs"),
	}

	for _, p := range checkPaths {
		if _, err := os.Stat(p); err == nil {
			d.Log.Info("Detected Nuxt project")
			return true
		}
	}

	d.Log.Debug("Nuxt project not detected")
	return false
}

func (d *Nuxt) GenerateDockerfile(path string, data ...map[string]string) ([]byte, error) {
	// Detect whether the project is SSG (nuxt generate) or SSR (default)
	mode := detectNuxtMode(path, d.Log)

	var nuxtTmpl string
	switch mode {
	case "static":
		d.Log.Info("Detected Nuxt static/SSG output mode")
		nuxtTmpl = nuxtStaticTemplate
	default:
		d.Log.Info("Detected Nuxt SSR mode (Nitro server)")
		nuxtTmpl = nuxtSSRTemplate
	}

	tmpl, err := template.New("Dockerfile").Parse(nuxtTmpl)
	if err != nil {
		return nil, fmt.Errorf("Failed to parse template: %w", err)
	}

	version, err := findNodeVersion(path, d.Log)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	templateData := map[string]string{
		"Version": *version,
	}
	if len(data) > 0 {
		maps.Copy(templateData, data[0])
	}

	if err := tmpl.Option("missingkey=zero").Execute(&buf, templateData); err != nil {
		return nil, fmt.Errorf("Failed to execute template: %w", err)
	}

	return buf.Bytes(), nil
}

// detectNuxtMode reads nuxt.config to determine SSR vs static output.
// Returns "static" if ssr: false or nitro.preset is set to a static preset.
// Returns "ssr" by default.
func detectNuxtMode(path string, log *slog.Logger) string {
	configFiles := []string{
		"nuxt.config.ts",
		"nuxt.config.js",
		"nuxt.config.mjs",
		"nuxt.config.mts",
		"nuxt.config.cjs",
	}

	for _, cf := range configFiles {
		fp := filepath.Join(path, cf)
		f, err := os.Open(fp)
		if err != nil {
			continue
		}
		defer f.Close()

		scanner := bufio.NewScanner(f)
		for scanner.Scan() {
			line := scanner.Text()
			// ssr: false  or  'ssr': false
			if strings.Contains(line, "ssr") && strings.Contains(line, "false") {
				log.Info("Detected Nuxt SSG mode via ssr: false")
				return "static"
			}
			// nitro preset for static: github-pages, cloudflare-pages, netlify-static, etc.
			staticPresets := []string{"github-pages", "cloudflare-pages", "netlify-static", "static"}
			for _, preset := range staticPresets {
				if strings.Contains(line, "preset") && strings.Contains(line, preset) {
					log.Info("Detected Nuxt static nitro preset: " + preset)
					return "static"
				}
			}
		}
	}

	return "ssr"
}

// nuxtSSRTemplate: for Nuxt 3 projects in SSR mode (default).
// Nuxt 3 uses Nitro which compiles to .output/server/index.mjs — a self-contained Node.js server.
var nuxtSSRTemplate = strings.TrimSpace(`
# syntax=docker/dockerfile:1
# Auto-generated by the "dockerfile-gen" CLI tool
# Please report any issues to: https://github.com/hivepaas/dockerfile-generator/issues
ARG NODE_VERSION={{.Version}}
ARG BUILDER=docker.io/library/node
ARG RUNNER=${BUILDER}:${NODE_VERSION}-slim
FROM ${RUNNER} AS base
RUN corepack enable

FROM base AS deps
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* bun.lockb* ./
ARG INSTALL_CMD=
RUN --mount=type=cache,target=/root/.npm \
    --mount=type=cache,target=/root/.local/share/pnpm/store \
    --mount=type=cache,target=/usr/local/share/.cache/yarn \
    {{.InstallMounts}}if [ ! -z "${INSTALL_CMD}" ]; then sh -c "$INSTALL_CMD"; \
  elif [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f bun.lockb ]; then npm i -g bun && bun install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else npm ci; fi

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Nuxt telemetry opt-out
ENV NUXT_TELEMETRY_DISABLED=1

ARG BUILD_CMD=
RUN --mount=type=cache,target=/app/.nuxt \
    --mount=type=cache,target=/root/.nuxt \
    {{.BuildMounts}}if [ ! -z "${BUILD_CMD}" ]; then sh -c "$BUILD_CMD"; \
  elif [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f bun.lockb ]; then npm i -g bun && bun run build; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  else npm run build; fi

# Nitro outputs a self-contained bundle — no node_modules needed at runtime
FROM base AS runtime
WORKDIR /app

ARG APT_EXTRA_PKGS=
RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates ${APT_EXTRA_PKGS} && apt-get clean && rm -f /var/lib/apt/lists/*_*
RUN update-ca-certificates 2>/dev/null || true
RUN groupadd -r nonroot && useradd -r -g nonroot nonroot
RUN chown -R nonroot:nonroot /app

# Only copy the Nitro output — fully self-contained
COPY --chown=nonroot:nonroot --from=builder /app/.output ./

# To run as root instead, pass build arg: --build-arg USER=root
ARG USER=nonroot:nonroot
USER ${USER}

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE ${PORT}

ENV NODE_ENV=production
ENV NUXT_TELEMETRY_DISABLED=1
CMD ["node", "./server/index.mjs"]
`)

// nuxtStaticTemplate: for Nuxt 3 projects using `nuxt generate` (SSG/static output).
// Output goes to .output/public and is served by a static web server.
var nuxtStaticTemplate = strings.TrimSpace(`
# syntax=docker/dockerfile:1
# Auto-generated by the "dockerfile-gen" CLI tool
# Please report any issues to: https://github.com/hivepaas/dockerfile-generator/issues
ARG NODE_VERSION={{.Version}}
ARG BUILDER=docker.io/library/node
ARG RUNNER=docker.io/joseluisq/static-web-server:2-debian
FROM ${BUILDER}:${NODE_VERSION}-slim AS deps
RUN corepack enable
WORKDIR /app
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* bun.lockb* ./
ARG INSTALL_CMD=
RUN --mount=type=cache,target=/root/.npm \
    --mount=type=cache,target=/root/.local/share/pnpm/store \
    --mount=type=cache,target=/usr/local/share/.cache/yarn \
    {{.InstallMounts}}if [ ! -z "${INSTALL_CMD}" ]; then sh -c "$INSTALL_CMD"; \
  elif [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f bun.lockb ]; then npm i -g bun && bun install; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  else npm ci; fi

FROM deps AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NUXT_TELEMETRY_DISABLED=1

ARG BUILD_CMD=
RUN --mount=type=cache,target=/app/.nuxt \
    --mount=type=cache,target=/root/.nuxt \
    {{.BuildMounts}}if [ ! -z "${BUILD_CMD}" ]; then sh -c "$BUILD_CMD"; \
  elif [ -f yarn.lock ]; then yarn generate; \
  elif [ -f package-lock.json ]; then npm run generate; \
  elif [ -f bun.lockb ]; then npm i -g bun && bun run generate; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run generate; \
  else npm run generate; fi

FROM ${RUNNER} AS runtime

ARG APT_EXTRA_PKGS=
RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates ${APT_EXTRA_PKGS} && apt-get clean && rm -f /var/lib/apt/lists/*_*

# Nuxt generate outputs to .output/public
COPY --from=builder /app/.output/public /public

ENV SERVER_PORT=8080
ENV SERVER_ROOT=/public
EXPOSE 8080
`)
